[package]
name = "day-twentyone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"

[dependencies.static_init]
version = "1.0.2"
features=["lock_statistics"]
