max_width = 120
use_small_heuristics = "Max"
chain_width = 60
edition = "2021"
newline_style = "Unix"

############################################################
#
# Unstable features
#
# condense_wildcard_suffixes = true
# enum_discrim_align_threshold = 10
# format_code_in_doc_comments = true
# imports_granularity = "Module"
# normalize_comments = true
# normalize_doc_attributes = true
# group_imports = "StdExternalCrate"
# struct_field_align_threshold = 20
# unstable_features = true
# wrap_comments = true